"""Criação tabela leituras

Revision ID: 39d0503e83bc
Revises: ddb8a61ef003
Create Date: 2025-06-19 11:52:55.750497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d0503e83bc'
down_revision = 'ddb8a61ef003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leituras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('umidade', sa.Float(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('pressao', sa.Float(), nullable=True),
    sa.Column('lote', sa.String(length=100), nullable=True),
    sa.Column('data_inicial', sa.DateTime(), nullable=True),
    sa.Column('data_final', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leituras')
    # ### end Alembic commands ###
